name: publish-say
on:
  push:
    tags:
      - "@snomiao/say*"
jobs:
  publish-say:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd packages/@snomiao/say
      - run: npm run build
      - run: npm run test
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
